import fs from 'node:fs';
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));
const layout=JSON.parse(fs.readFileSync('streamdeck/layout.json','utf8'));
const bindings=new Map(pkg.contributes.keybindings.map(b=>[b.command,b.key]));
const titles=new Map(pkg.contributes.commands.map(b=>[b.command,b.title]));
const fallback=JSON.parse(fs.readFileSync('streamdeck/keybindings-fallback.json','utf8'));
for(const row of layout.rows)for(const button of row){button.key=bindings.get(button.command);if(!button.key)throw new Error('Missing binding: '+button.command)}
fs.writeFileSync('streamdeck/layout.json',JSON.stringify(layout,null,2)+'\n');
const csv=['device_row,column,label,command,key'];
layout.rows.forEach((row,r)=>row.forEach((b,c)=>csv.push([r+2,c+1,b.label,b.command,b.key].map(x=>'"'+String(x).replaceAll('"','""')+'"').join(','))));
fs.writeFileSync('streamdeck/layout.csv',csv.join('\n')+'\n');
let doc=`# Keybindings and Stream Deck XL mapping\n\nThe manifest in package.json is authoritative. Run npm run mapping after changing it.\nAll 32 commands are available in the Command Palette. Hotkeys are disabled during Quick Pick input. Actions that execute code additionally require a trusted workspace.\n\n## Default shortcuts\n\nCtrl means the Control key on Windows, Linux and macOS. No Command-key substitution is made on macOS.\n\n| Command | Action | Default hotkey | Fallback chord |\n| --- | --- | --- | --- |\n`;
for(const [id,key] of bindings)doc+=`| ${id} | ${titles.get(id)} | ${key} | ${fallback.find(b=>b.command===id)?.key} |\n`;
doc+=`\n## XL page\n\nThe XL has four physical rows. Keep physical row 1 for your existing page navigation. The following actions occupy physical rows 2 to 4.\n\n| Physical row | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n`;
layout.rows.forEach((row,i)=>{doc+=`| ${i+2} | ${row.map(b=>b.label).join(' | ')} |\n`});
doc+=`\nFormat invokes the document formatter. Lint, Check and Document are R-package actions in v1. Stop Execution, Stop App, Checkout, Test Current File, Load All, Style Package and Show Log can be placed on another page.\n\n## Set up Elgato Stream Deck\n\n1. Install the VSIX in the Positron or remote Workbench session.\n2. Confirm a Positron Deck command works from the Command Palette.\n3. In the local Windows Stream Deck application, assign the built-in System > Hotkey action to each button. Use the key column in layout.csv. The extension and the Stream Deck software do not communicate directly.\n4. If the key picker cannot enter F13 through F24, use the fallback below. Do not depend on recording keys your keyboard cannot generate.\n5. Focus the Positron desktop window or the browser tab containing the Workbench IDE before pressing a button.\n6. Run Developer: Toggle Keyboard Shortcuts Troubleshooting in the IDE and check that the expected key and positronDeck command arrive. Test on the actual Windows/browser combination.\n\nF13 through F24 exist in the current VS Code keycode implementation, including Windows VK mappings. The documentation only lists F1 through F19. Neither source-level support nor a valid manifest proves delivery through every browser, OS, keyboard layout or Stream Deck software version. These defaults are not a cross-platform hardware certification.\n\n## Fallback for browsers and key pickers\n\nMerge streamdeck/keybindings-fallback.json into the IDE's **user** keybindings.json (do not replace existing bindings). These are additional bindings, not a workspace settings file.\n\nFor each Stream Deck button create a built-in Multi Action:\n\n1. Hotkey: Ctrl+Alt+Shift+F12.\n2. Delay: 100 ms as an initial setting; increase if your session needs it.\n3. Hotkey: the second key shown in the fallback column, without modifiers.\n\nBoth strokes must reach the same focused IDE window. Use Escape to cancel an incomplete chord. If your OS intercepts the prefix, record a different unused prefix in the Keyboard Shortcuts editor and change it in both places. No hotkey combination is universally collision-free.\n\n## Profile format\n\nlayout.json and layout.csv are mapping files, not .streamDeckProfile files. This release does not fabricate an Elgato profile without a known-good export and an import test. A native exported profile can be contributed after validation with the supported Stream Deck software version. No Stream Deck plugin is needed for v1.\n`;
fs.writeFileSync('docs/KEYBINDINGS.md',doc);
const short=[['Run Selection','Run File','Test','Render','Run App','Terminal','Console','Commands'],['Stage All','Commit','Pull','Push','Sync','Diff','Git Log','Source Control'],['Format','Lint','Check','Document','Preview','Restart','Problems','Deploy']];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;');
let svg='<svg xmlns="http://www.w3.org/2000/svg" width="1440" height="610" viewBox="0 0 1440 610"><rect width="1440" height="610" rx="20" fill="#101827"/><text x="40" y="52" fill="#edf5ff" font-family="sans-serif" font-size="28">Positron Deck · Stream Deck XL</text><text x="40" y="82" fill="#94a9c3" font-family="sans-serif" font-size="16">Top row reserved for page navigation · 24 development actions below</text>';
for(let r=0;r<4;r++)for(let c=0;c<8;c++){
 const x=40+c*171,y=110+r*119;svg+=`<rect x="${x}" y="${y}" width="157" height="103" rx="12" fill="${r===0?'#202c40':r===1?'#163c4c':r===2?'#303753':'#354033'}" stroke="#47617d"/>`;
 const label=r===0?'Page '+(c+1):short[r-1][c];const key=r===0?'Your navigation':layout.rows[r-1][c].key.replace('ctrl+alt+shift+','C+A+S+').replace('ctrl+shift+','C+S+').toUpperCase();
 svg+=`<text x="${x+78.5}" y="${y+42}" text-anchor="middle" fill="#edf5ff" font-family="sans-serif" font-size="17">${esc(label)}</text><text x="${x+78.5}" y="${y+72}" text-anchor="middle" fill="#a5bfd2" font-family="sans-serif" font-size="13">${esc(key)}</text>`;
}
svg+='</svg>';fs.writeFileSync('streamdeck/layout.svg',svg);
